/**
 * \package exceptions
 * \brief Package of classes that create runtime exception objects for use when an error is encountered
 * 
 * Package of classes that create runtime exception objects for use when an error is encountered. This package is part of iDynoMiCS v1.2, governed by the 
 * CeCILL license under French law and abides by the rules of distribution of free software.  You can use, modify and/ or redistribute 
 * iDynoMiCS under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL  "http://www.cecill.info".
 */
package exceptions;

/**
 * \brief Creates the runtime exceptions that are generated by iDynoMiCS when an error is encountered
 * 
 * Creates the runtime exceptions that are generated by iDynoMiCS when an error is encountered
 * 
 * @author Joao Xavier (xavierj@mskcc.org), Memorial Sloan-Kettering Cancer Center (NY, USA)
 */
public class ModelRuntimeException extends RuntimeException 
{

	/**
	 * Serial version ID declared as this class is serializable
	 */
	private static final long serialVersionUID = 666L;
	

	/**
	 *  \brief Creates a generic runtime exception when an error is encountered
	 *  
	 *  Creates a generic runtime exception when an error is encountered
	 */
	public ModelRuntimeException() 
	{
		super();
	}
	
	
	/**
	 * \brief Creates a runtime exception when an error is encountered, but with a specific error message
	 * 
	 * Creates a runtime exception when an error is encountered, but with a specific error message
	 */
	public ModelRuntimeException(String message) 
	{
		super(message);
	}
	
	/**
	 * \brief Creates an exception to be thrown when a given number is not valid in runtime
	 * 
	 * Creates an exception to be thrown when a given number is not valid in runtime
	 * 
	 * @param f
	 */
	public ModelRuntimeException(double f) {
		super(f + " is not a valid number");
	}
}
